/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mynfs.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
my_nfs_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		my_open_params my_open_1_arg;
		my_creat_params my_creat_1_arg;
		my_read_params my_read_1_arg;
		my_write_params my_write_1_arg;
		my_lseek_params my_lseek_1_arg;
		my_close_params my_close_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case my_open:
		_xdr_argument = (xdrproc_t) xdr_my_open_params;
		_xdr_result = (xdrproc_t) xdr_my_open_creat_results;
		local = (char *(*)(char *, struct svc_req *)) my_open_1_svc;
		break;

	case my_creat:
		_xdr_argument = (xdrproc_t) xdr_my_creat_params;
		_xdr_result = (xdrproc_t) xdr_my_open_creat_results;
		local = (char *(*)(char *, struct svc_req *)) my_creat_1_svc;
		break;

	case my_read:
		_xdr_argument = (xdrproc_t) xdr_my_read_params;
		_xdr_result = (xdrproc_t) xdr_my_read_results;
		local = (char *(*)(char *, struct svc_req *)) my_read_1_svc;
		break;

	case my_write:
		_xdr_argument = (xdrproc_t) xdr_my_write_params;
		_xdr_result = (xdrproc_t) xdr_my_write_results;
		local = (char *(*)(char *, struct svc_req *)) my_write_1_svc;
		break;

	case my_lseek:
		_xdr_argument = (xdrproc_t) xdr_my_lseek_params;
		_xdr_result = (xdrproc_t) xdr_my_lseek_results;
		local = (char *(*)(char *, struct svc_req *)) my_lseek_1_svc;
		break;

	case my_close:
		_xdr_argument = (xdrproc_t) xdr_my_close_params;
		_xdr_result = (xdrproc_t) xdr_my_close_results;
		local = (char *(*)(char *, struct svc_req *)) my_close_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (MY_NFS, MY_NFS_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, MY_NFS, MY_NFS_V1, my_nfs_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MY_NFS, MY_NFS_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, MY_NFS, MY_NFS_V1, my_nfs_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MY_NFS, MY_NFS_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
