/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <errno.h>
#include "mynfs.h"


int _my_open(CLIENT* clnt, char* p, my_access ma) {
	my_open_creat_results  *result_1;
	my_open_params  my_open_1_arg;

	my_open_1_arg.path = p;
	my_open_1_arg.my_access_flag = ma;

	result_1 = my_open_1(&my_open_1_arg, clnt);
	if (result_1 == (my_open_creat_results *) NULL) {
		clnt_perror (clnt, "open call failed");
	} else if (result_1->status == -1) {
		errno = result_1->my_open_creat_results_u.my_errno;
		perror("--SERVER open error");
	} else {
		printf("OPEN DONE, %s -> fd = %d\n", p, result_1->my_open_creat_results_u.fd);
		return result_1->my_open_creat_results_u.fd;
	}
	return -1;
}

int _my_creat(CLIENT* clnt, char* p) {
	my_open_creat_results  *result_2;
	my_creat_params  my_creat_1_arg;

	my_creat_1_arg.path = p;

	result_2 = my_creat_1(&my_creat_1_arg, clnt);
	if (result_2 == (my_open_creat_results *) NULL) {
		clnt_perror (clnt, "creat call failed");
	} else if (result_2->status == -1) {
		errno = result_2->my_open_creat_results_u.my_errno;
		perror("--SERVER creat error--");
	} else {
		printf("CREAT DONE, %s -> fd = %d\n", p, result_2->my_open_creat_results_u.fd);
		return result_2->my_open_creat_results_u.fd;
	}
	return -1;
}

int _my_read(CLIENT* clnt, int f, int c) {
	my_read_results  *result_3;
	my_read_params  my_read_1_arg;

	my_read_1_arg.fd = f;
	my_read_1_arg.count = c;

	result_3 = my_read_1(&my_read_1_arg, clnt);
	if (result_3 == (my_read_results *) NULL) {
		clnt_perror (clnt, "read call failed");
	} else if (result_3->status == -1) {
		errno = result_3->my_read_results_u.my_errno;
		perror("--SERVER read error");
	} else {
		printf("(fd %d) READ DONE: %s\n", f, result_3->my_read_results_u.buf);
		return 0;
	}
	return -1;
}

int _my_write(CLIENT* clnt, int f, char* b) {
	my_write_results  *result_4;
	my_write_params  my_write_1_arg;

	my_write_1_arg.fd = f;
	my_write_1_arg.buf = b;
	my_write_1_arg.buf_size = strlen(my_write_1_arg.buf);

	result_4 = my_write_1(&my_write_1_arg, clnt);
	if (result_4 == (my_write_results *) NULL) {
		clnt_perror (clnt, "write call failed");
	} else if (result_4->status == -1) {
		errno = result_4->my_write_results_u.my_errno;
		perror("--SERVER write error");
	} else {
		printf("(fd %d) WRITE DONE, %s (%dB)\n", f, b, result_4->my_write_results_u.bytes_written);
		return 0;
	}
	return -1;
}

int _my_lseek(CLIENT* clnt, int f, int o, my_whence mw) {
	my_lseek_results  *result_5;
	my_lseek_params  my_lseek_1_arg;

	my_lseek_1_arg.fd = f;
	my_lseek_1_arg.offset = o;
	my_lseek_1_arg.my_whence_flag = mw;

	result_5 = my_lseek_1(&my_lseek_1_arg, clnt);
	if (result_5 == (my_lseek_results *) NULL) {
		clnt_perror (clnt, "lseek call failed");
	} else if (result_5->status == -1) {
		errno = result_5->my_lseek_results_u.my_errno;
		perror("--SERVER lseek error");
	} else {
		printf("(fd %d) LSEEK DONE, current location: %d\n", f, result_5->my_lseek_results_u.offset_location);
		return result_5->my_lseek_results_u.offset_location;
	}
	return -1;
}

int _my_close(CLIENT* clnt, int f) {
	my_close_results  *result_6;
	my_close_params  my_close_1_arg;

	my_close_1_arg.fd = f;

	result_6 = my_close_1(&my_close_1_arg, clnt);
	if (result_6 == (my_close_results *) NULL) {
		clnt_perror (clnt, "close call failed");
	} else if (result_6->status == -1) {
		errno = result_6->my_close_results_u.my_errno;
		perror("--SERVER close error");
	} else {
		printf("(fd %d) CLOSE DONE\n", f);
		return 0;
	}
	return -1;
}

CLIENT* get_client_from_host(char *host) {
	CLIENT *c;

	#ifndef	DEBUG
	c = clnt_create (host, MY_NFS, MY_NFS_V1, "udp");
	if (c == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	#endif	/* DEBUG */
	return c;

}

void destroy_client(CLIENT *c) {
	#ifndef	DEBUG
	clnt_destroy (c);
	#endif	 /* DEBUG */
}

void my_nfs_1(char *host) {
	CLIENT *clnt = get_client_from_host(host);

	int mo = _my_open(clnt, "test2.txt", _O_RDWR);
	int mcr = _my_creat(clnt, "test3.txt");
	int mr = _my_read(clnt, mo, 25);
	int mw = _my_write(clnt, mo, "qwe+");
	int ml = _my_lseek(clnt, mo, 2, _SEEK_SET);
	int mr2 = _my_read(clnt, mo, 3);
	int mcl = _my_close(clnt, mo);
	int mcl2 = _my_close(clnt, mcr);

	destroy_client(clnt);
}


int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	if (argc == 2) {
		// demo
		my_nfs_1 (host);
	} else {
		CLIENT* clnt = get_client_from_host(host);
		if (strcmp(argv[2], "open") == 0) {
			my_access maf = _O_RDWR;
			if (strcmp(argv[4], "_O_RDONLY") == 0) maf = _O_RDONLY;
			if (strcmp(argv[4], "O_WRONLY") == 0) maf = _O_WRONLY;
			_my_open(clnt, argv[3], maf);
		}
		else if (strcmp(argv[2], "creat") == 0) {
			_my_creat(clnt, argv[3]);
		}
		else if (strcmp(argv[2], "read") == 0) {
			_my_read(clnt, atoi(argv[3]), atoi(argv[4]));
		}
		else if (strcmp(argv[2], "write") == 0) {
			_my_write(clnt, atoi(argv[3]), argv[4]);
		}
		else if (strcmp(argv[2], "lseek") == 0) {
			my_whence mw = _SEEK_SET;
			if (strcmp(argv[4], "SEEK_CUR") == 0) mw = _SEEK_CUR;
			if (strcmp(argv[4], "SEEK_END") == 0) mw = _SEEK_END;
			_my_lseek(clnt, atoi(argv[3]), atoi(argv[4]), mw);
		}
		else if (strcmp(argv[2], "close") == 0) {
			_my_close(clnt, atoi(argv[3]));
		}
		else {
			printf("bad command\n");
		}
		destroy_client(clnt);
	}

	exit (0);
}
