/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include "mynfs.h"

my_open_creat_results *
my_open_1_svc(my_open_params *argp, struct svc_req *rqstp)
{
	static my_open_creat_results  result;

	printf("open %s\n", argp->path);

	int res;
	switch (argp->my_access_flag) {
		case _O_RDONLY:
			res = open(argp->path, O_RDONLY);
			break;
		case _O_WRONLY:
			res = open(argp->path, O_WRONLY);
			break;
		case _O_RDWR:
			res = open(argp->path, O_RDWR);
			break;
		default:
			res = -1;
			break;
	}
	result.status = res;
	if (res != -1) {
		result.my_open_creat_results_u.fd = res;
	} else {
		result.my_open_creat_results_u.my_errno = errno;
	}

	return &result;
}

my_open_creat_results *
my_creat_1_svc(my_creat_params *argp, struct svc_req *rqstp)
{
	static my_open_creat_results  result;

	printf("creat %s\n", argp->path);

	return &result;
}

my_read_results *
my_read_1_svc(my_read_params *argp, struct svc_req *rqstp)
{
	static my_read_results  result;

	printf("read\n");
	//result.status = 1;
	//result.my_read_results_u.buf = "readable";
	result.status = -1;
	result.my_read_results_u.my_errno = EINVAL;

	return &result;
}

my_write_results *
my_write_1_svc(my_write_params *argp, struct svc_req *rqstp)
{
	static my_write_results  result;

	printf("write %s\n", argp->buf);

	return &result;
}

my_lseek_results *
my_lseek_1_svc(my_lseek_params *argp, struct svc_req *rqstp)
{
	static my_lseek_results  result;

	printf("lseek\n");

	return &result;
}

my_close_results *
my_close_1_svc(my_close_params *argp, struct svc_req *rqstp)
{
	static my_close_results  result;

	printf("close\n");

	return &result;
}
