/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mynfs.h"

bool_t
xdr_my_access (XDR *xdrs, my_access *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_whence (XDR *xdrs, my_whence *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_open_params (XDR *xdrs, my_open_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, ~0))
		 return FALSE;
	 if (!xdr_my_access (xdrs, &objp->my_access_flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_creat_params (XDR *xdrs, my_creat_params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->path, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_read_params (XDR *xdrs, my_read_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->count))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_write_params (XDR *xdrs, my_write_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->buf, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->buf_size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_lseek_params (XDR *xdrs, my_lseek_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_my_whence (xdrs, &objp->my_whence_flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_close_params (XDR *xdrs, my_close_params *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fd))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_my_open_creat_results (XDR *xdrs, my_open_creat_results *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case -1:
		 if (!xdr_int (xdrs, &objp->my_open_creat_results_u.my_errno))
			 return FALSE;
		break;
	default:
		 if (!xdr_int (xdrs, &objp->my_open_creat_results_u.fd))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_my_read_results (XDR *xdrs, my_read_results *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case -1:
		 if (!xdr_int (xdrs, &objp->my_read_results_u.my_errno))
			 return FALSE;
		break;
	default:
		 if (!xdr_string (xdrs, &objp->my_read_results_u.buf, ~0))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_my_write_results (XDR *xdrs, my_write_results *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case -1:
		 if (!xdr_int (xdrs, &objp->my_write_results_u.my_errno))
			 return FALSE;
		break;
	default:
		 if (!xdr_int (xdrs, &objp->my_write_results_u.bytes_written))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_my_lseek_results (XDR *xdrs, my_lseek_results *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case -1:
		 if (!xdr_int (xdrs, &objp->my_lseek_results_u.my_errno))
			 return FALSE;
		break;
	default:
		 if (!xdr_int (xdrs, &objp->my_lseek_results_u.offset_location))
			 return FALSE;
		break;
	}
	return TRUE;
}

bool_t
xdr_my_close_results (XDR *xdrs, my_close_results *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	switch (objp->status) {
	case -1:
		 if (!xdr_int (xdrs, &objp->my_close_results_u.my_errno))
			 return FALSE;
		break;
	default:
		 if (!xdr_int (xdrs, &objp->my_close_results_u.success))
			 return FALSE;
		break;
	}
	return TRUE;
}
